sonar.projectKey=TimeSheetLeaveManagementSystem
sonar.projectName=TimeSheetLeaveManagementSystem
sonar.sourceEncoding=UTF-8
sonar.java.source=17

sonar.sources=\
  auth-service/src/main/java,\
  admin-service/src/main/java,\
  leave-service/src/main/java,\
  timesheet-service/src/main/java,\
  api-gateway/src/main/java,\
  Config-Server/src/main/java,\
  EurekaServer/src/main/java,\
  common/src/main/java

sonar.tests=\
  auth-service/src/test/java,\
  admin-service/src/test/java,\
  leave-service/src/test/java,\
  timesheet-service/src/test/java,\
  api-gateway/src/test/java,\
  Config-Server/src/test/java,\
  EurekaServer/src/test/java,\
  common/src/test/java

sonar.java.binaries=\
  auth-service/target/classes,\
  admin-service/target/classes,\
  leave-service/target/classes,\
  timesheet-service/target/classes,\
  api-gateway/target/classes,\
  Config-Server/target/classes,\
  EurekaServer/target/classes,\
  common/target/classes

sonar.java.test.binaries=\
  auth-service/target/test-classes,\
  admin-service/target/test-classes,\
  leave-service/target/test-classes,\
  timesheet-service/target/test-classes,\
  api-gateway/target/test-classes,\
  Config-Server/target/test-classes,\
  EurekaServer/target/test-classes,\
  common/target/test-classes

sonar.coverage.jacoco.xmlReportPaths=\
  common/target/site/jacoco/jacoco.xml,\
  auth-service/target/site/jacoco/jacoco.xml,\
  admin-service/target/site/jacoco/jacoco.xml,\
  leave-service/target/site/jacoco/jacoco.xml,\
  timesheet-service/target/site/jacoco/jacoco.xml,\
  api-gateway/target/site/jacoco/jacoco.xml,\
  Config-Server/target/site/jacoco/jacoco.xml,\
  EurekaServer/target/site/jacoco/jacoco.xml

sonar.exclusions=\
  **/target/**,\
  **/mvnw,\
  **/mvnw.cmd,\
  **/.mvn/**,\
  **/Dockerfile,\
  **/k8s/**,\
  **/.settings/**,\
  **/.classpath

sonar.coverage.exclusions=\
  **/*Application.java,\
  **/config/**,\
  **/dto/**,\
  **/entity/**,\
  **/exception/**,\
  **/client/fallback/**,\
  **/messaging/**,\
  **/event/**

sonar.coverage.inclusions=\
  **/controller/**,\
  **/service/**,\
  **/security/**

sonar.cpd.exclusions=\
  **/dto/**,\
  **/entity/**,\
  **/config/**,\
  **/client/fallback/**,\
  **/*Application.java
